CREATE TABLE fahrzeuge (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  license TEXT NOT NULL,
  color TEXT NOT NULL,
  tuv TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
